#!/bin/bash
#Create empty directories
if [ ! -d "/opt/ccu.io/tmp" ]; then
  mkdir /opt/ccu.io/tmp
fi
if [ ! -d "/opt/ccu.io/datastore" ]; then
  mkdir /opt/ccu.io/datastore
fi
if [ ! -d "/opt/ccu.io/log" ]; then
  mkdir /opt/ccu.io/log
fi
#Set rights
echo "Set permissions..."
find /opt/ccu.io/ -type d -exec chmod 777 {} \;
find /opt/ccu.io/ -type f -exec chmod 777 {} \;
chown -R @@user:@@user /opt/ccu.io/
chmod 777 /etc/init.d/ccu.io.sh
chown root:root /etc/init.d/ccu.io.sh
#Check if user @@user exists
if [ $(cat /etc/passwd | grep "/home" |cut -d: -f1 | grep '^@@user$' | wc -l) -eq 0 ]
then
    read -p "User @@user does not exist. Create?" yn
    case $yn in
        [Yy]* ) apt-get install sudo;adduser @@user;adduser @@user sudo;visudo -f /etc/sudoers;user ALL=(ALL) NOPASSWD:ALL; break;;
        [Nn]* ) echo "The start of CCU.IO at system start will not work!";;
        * ) echo "Please answer yes or no.";;
    esac
fi

# Start the service!
echo "Start ccu.io..."
node /opt/ccu.io/ccu.io-server.js start
