#!/bin/bash
#Create empty directories
if [ ! -d "/opt/ccu.io/tmp" ]; then
  mkdir /opt/ccu.io/tmp
fi
if [ ! -d "/opt/ccu.io/datastore" ]; then
  mkdir /opt/ccu.io/datastore
fi
if [ ! -d "/opt/ccu.io/log" ]; then
  mkdir /opt/ccu.io/log
fi
#Set rights
echo "Set permissions..."
find /opt/ccu.io/ -type d -exec chmod 777 {} \;
find /opt/ccu.io/ -type f -exec chmod 777 {} \;
chown -R @@user:@@user /opt/ccu.io/
chmod 777 /etc/init.d/ccu.io.sh
chown root:root /etc/init.d/ccu.io.sh
# Start the service!
echo "Start ccu.io..."
node /opt/ccu.io/ccu.io-server.js start
